"""`docs/openapi.json` is generated by `linkplane.api.openapi`; the file must equal the generator."""

import json
import unittest

from linkplane.api import actions, openapi, security
from linkplane.core import errors


class OpenApiPinTests(unittest.TestCase):
    def setUp(self):
        self.spec = json.loads(openapi.DOC_PATH.read_text())

    def test_the_committed_document_is_exactly_what_the_generator_produces(self):
        self.assertEqual(self.spec, openapi.build_spec(), "regenerate with: python -m linkplane.api.openapi")

    def test_every_route_is_documented_and_nothing_else(self):
        self.assertEqual(openapi.routes_served(), openapi.routes_in(self.spec))

    def test_public_vocabulary_and_codes_are_pinned(self):
        self.assertEqual(set(self.spec["x-actions"]), set(actions.ACTIONS))
        self.assertEqual(self.spec["x-public-actions"], {"backup": "backup.photos", "clipboard-sync": "clipboard.sync", "send": "files.send"})
        self.assertEqual(self.spec["components"]["schemas"]["Job"]["properties"]["action"]["enum"], ["backup.photos", "clipboard.sync", "files.send"])
        self.assertEqual(self.spec["x-status-for-code"], dict(sorted(security.STATUS_FOR_CODE.items())))
        codes = {v for k, v in vars(errors).items() if k.isupper() and isinstance(v, str) and v.startswith("LP-")}
        self.assertEqual(set(self.spec["components"]["schemas"]["Error"]["properties"]["error"]["properties"]["code"]["enum"]), codes)
        self.assertEqual(self.spec["info"]["x-protocol"], "linkplane.api/1")
        self.assertIn("/v1/rules/reload", self.spec["paths"])
        self.assertNotIn("requestBody", self.spec["paths"]["/v1/rules/reload"]["post"])  # reload takes nothing
